Repository codenation-dev/squad-2-ad-python-2, pull requests merged in 2019-07, with the labels that each got.

#3 Criando validação para valores negativos
  planos/models.py
  planos/serializers.py
  planos/tests.py
  planos/validators.py
Labels: enhancement

#5 Criar os models de acordo com as novas especificações do projeto #4
  Pipfile
  Pipfile.lock
  core/settings.py
  core/urls.py
  planos/migrations/0002_auto_20190715_1338.py
  vendas/__init__.py
  vendas/admin.py
  vendas/apps.py
  vendas/migrations/0001_initial.py
  vendas/migrations/__init__.py
  vendas/models.py
  vendas/serializers.py
  vendas/tests.py
  vendas/views.py
  vendedores/__init__.py
  vendedores/admin.py
  vendedores/apps.py
  vendedores/migrations/0001_initial.py
  vendedores/migrations/0002_auto_20190715_1419.py
  vendedores/migrations/0003_auto_20190715_1523.py
  vendedores/migrations/0004_auto_20190715_1603.py
  vendedores/migrations/__init__.py
  vendedores/models.py
  vendedores/serializers.py
  vendedores/tests.py
  vendedores/validators.py
  vendedores/views.py
Labels: enhancement

#6 Corrigindo bug ao criar plano via DRF
  planos/serializers.py
Labels: bug

#15 Venda única por mês e vendedor
  vendas/migrations/0002_auto_20190725_1037.py
  vendas/models.py
Labels: bug

#16 Criar um endpoint: checar_comissao
  .gitignore
  core/urls.py
  vendas/views.py
Labels: enhancement

#14 Calcular comissao venda
  planos/tests.py
  vendas/models.py
  vendas/serializers.py
  vendas/tests.py
  vendas/validators.py
  vendedores/tests.py
Labels: enhancement

#18 Inclusão de comissoes/1
  core/urls.py
  vendedores/serializers.py
  vendedores/views.py
Labels: enhancement

#19 deploy no Heroku
  Pipfile
  Pipfile.lock
  Procfile
  core/settings.py
  requirements.txt
Labels: enhancement

#22 Criando testes unitários para API de notificação
  vendas/tests.py
Labels: enhancement

#12 Documentação RAML dos endpoints
  endpoints.raml
Labels: documentation
